### PR TITLE
Clear previously fetched models before render

### PR DESCRIPTION
**Pull request by cheshir**

### CODE REVIEW

**Comment by kartik-v** [comment]
There is a new boolean property `initProvider` included which defaults to `false`.

Set it to `true` if you wish to clear previously fetched models.

**Comment by kartik-v** [comment]
Check the [documentation for various settings for the extension](http://demos.krajee.com/export#settings).

**Comment by cheshir** [comment]
When I'm try to set initProvider property I get error:
Getting unknown property: kartik\export\ExportMenu::initProvider
Also, I can't find initProvider property or string literal in source code.

**Comment by kartik-v** [comment]
You seem to have the wrong source code... you need to get the updated code from dev-master.

**Comment by cheshir** [comment]
Yes, you're right. I have old version.

**Comment by magallo286** [comment]
not know whether this parameter is the wornig.   but if i do several submit with parameter different, the information not change follow downloading data of the first consultation

**Comment by magallo286** [comment]
not know whether this parameter is the error.   but if i do several submit with parameter different, the information not change follow downloading data of the first consultation

**Pull request closed without merging**
